### ISSUE TITLE
Will this work with xgboost 0.82?

### ISSUE THREAD

**Issue by michael1albq** [Nexosis/alpine-xgboost#5]
I'm trying to work with a feature made available in 0.82. I tried replacing -b 0.81 with -b 0.82 but ran into compile errors: 

Makefile:31: MAKE [make] - checked OK
g++ -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/learner.o src/learner.cc >build/learner.d
g++ -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/logging.o src/logging.cc >build/logging.d
g++ -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/objective/regression_obj.o src/objective/regression_obj.cc >build/objective/regression_obj.d
g++ -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/objective/rank_obj.o src/objective/rank_obj.cc >build/objective/rank_obj.d
In file included from dmlc-core/include/dmlc/./serializer.h:22:0,
                 from dmlc-core/include/dmlc/io.h:445,
                 from src/learner.cc:7:
dmlc-core/include/dmlc/././endian.h:24:6: error: #error "Unable to determine endianness of your machine; use CMake to compile"
     #error "Unable to determine endianness of your machine; use CMake to compile"
      ^~~~~
In file included from dmlc-core/include/dmlc/./serializer.h:22:0,
                 from dmlc-core/include/dmlc/io.h:445,
                 from rabit/include/rabit/./internal/../serializable.h:12,
                 from rabit/include/rabit/./internal/engine.h:10,
                 from rabit/include/rabit/rabit.h:32,
                 from src/logging.cc:7:
dmlc-core/include/dmlc/././endian.h:24:6: error: #error "Unable to determine endianness of your machine; use CMake to compile"
     #error "Unable to determine endianness of your machine; use CMake to compile"
      ^~~~~
make: *** [Makefile:142: build/logging.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from dmlc-core/include/dmlc/././serializer.h:22:0,
                 from dmlc-core/include/dmlc/./io.h:445,
                 from dmlc-core/include/dmlc/data.h:14,
                 from include/xgboost/./data.h:11,
                 from include/xgboost/objective.h:15,
                 from src/objective/regression_obj.cu:10,
                 from src/objective/regression_obj.cc:17:
dmlc-core/include/dmlc/./././endian.h:24:6: error: #error "Unable to determine endianness of your machine; use CMake to compile"
     #error "Unable to determine endianness of your machine; use CMake to compile"
      ^~~~~
In file included from dmlc-core/include/dmlc/././serializer.h:22:0,
                 from dmlc-core/include/dmlc/./io.h:445,
                 from dmlc-core/include/dmlc/data.h:14,
                 from include/xgboost/./data.h:11,
                 from include/xgboost/objective.h:15,
                 from src/objective/rank_obj.cc:9:
dmlc-core/include/dmlc/./././endian.h:24:6: error: #error "Unable to determine endianness of your machine; use CMake to compile"
     #error "Unable to determine endianness of your machine; use CMake to compile"
      ^~~~~
make: *** [Makefile:142: build/objective/regression_obj.o] Error 1
make: *** [Makefile:142: build/objective/rank_obj.o] Error 1
make: *** [Makefile:142: build/learner.o] Error 1

**Comment by eterna2** [comment]
I fix this for 0.82 by updating dmlc-core, because the backtrace logic detection is fixed after 0.82.
And I have to use cmake instead of make

https://github.com/dmlc/dmlc-core/pull/487

```docker
RUN apk add --update --no-cache \
    --virtual=.build-dependencies \
    git make gfortran g++ cmake \
    && mkdir /src \
    && cd /src \
    && git clone --depth 1 --recursive -b v$XGBOOST_VERSION https://github.com/dmlc/xgboost \
    && ln -s locale.h /usr/include/xlocale.h \
    # update dmlc-core to have better backtrace detection logic
    # so that musl in alpine can work
    # https://github.com/dmlc/dmlc-core/pull/487
    && cd /src/xgboost/dmlc-core; git checkout master && git pull \ 
    && cd /src/xgboost; mkdir build; cd build; cmake ..; make -j4 \
    && cd /src/xgboost/python-package \
    && pip install numpy~=1.15.4 \
    && pip install scipy~=1.2.0 \
    && pip install pandas~=0.23.4 \
    && pip install scikit-learn~=0.20.2 \    
    && python3 setup.py install \
    && rm /usr/include/xlocale.h \
    && rm -r /root/.cache \
    && rm -rf /src \
    apk del .build-dependencies
```

**Comment by michael1albq** [comment]
Tried running this 

`
Cloning into 'xgboost'...
warning: Could not find remote branch v to clone.
fatal: Remote branch v not found in upstream origin
fatal: not a git repository (or any of the parent directories): .git
CMake Error: The source directory "/src" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
make: *** No targets specified and no makefile found.  Stop.
The command '/bin/sh -c apk add --update --no-cache     --virtual=.build-dependencies     git make gfortran g++ cmake     && mkdir /src     && cd /src     && git clone --depth 1 --recursive -b v$XGBOOST_VERSION https://github.com/dmlc/xgboost     && ln -s locale.h /usr/include/xlocale.h     && cd /src/xgboost/dmlc-core; git checkout master && git pull     && cd /src/xgboost; mkdir build; cd build; cmake ..; make -j4     && cd /src/xgboost/python-package     && pip install numpy~=1.15.4     && pip install scipy~=1.2.0     && pip install pandas~=0.23.4     && pip install scikit-learn~=0.20.2     && python3 setup.py install     && rm /usr/include/xlocale.h     && rm -r /root/.cache     && rm -rf /src     apk del .build-dependencies' returned a non-zero code: 2 `
